### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/category_encoders#247]
Hi @wdm0006, I am handing over the management of the repository.

The repository is prepared for a new release, which is long due since the last published release doesn't work so well under Pandas 1.0.0 (the master branch works fine). I hope you will find time to manage the repository.

**Comment by wdm0006** [comment]
Hey @janmotl. Thanks for all the work so far. I can take a look at a release (and maybe setting up an action to handle releases in the future), I've also opened an issue to solicit maintainers as I really don't have the time to keep up with this very closely these days.

**Comment by wdm0006** [comment]
Ok, after some minor turmoil I've moved all the CI tasks to github actions, so that others can more easily modify or add to them. 

* The test suite will run in 4 versions of python on all commits to master and PRs. 
* The docs will update on any push to master (we could modify this to only happen on release, I could go either way).
* Build and publication to PyPI will happen anytime a release is created via the releases section on github, so it's now pretty easy to do also. 

With that, the docs are hosted and up to date, and v2.2.2 is out here:

https://pypi.org/project/category-encoders/
