### ISSUE TITLE
MEstimateEncoder: understanding

### ISSUE THREAD

**Issue by loveis98** [scikit-learn-contrib/category_encoders#262]
## Expected Behavior
MEstimateEncoder works only for binary target

## Actual Behavior
MEstimateEncoder works with regression tasks. Could you explain please, how it works?

## Specifications

  - Version: 2.2.2

**Comment by janmotl** [comment]
One of the references could be helpful:
    https://en.wikipedia.org/wiki/Additive_smoothing#Generalized_to_the_case_of_known_incidence_rates

I updated the documentation in all supervised encoders to state, which targets are supported a810a4b7abfce9fc4eb7fc401e3d37f2c1c6e402.

**Comment by PaulWestenthanner** [comment]
In binary case, the idea is to encode a category with a blend of the prior probability and the probability of this specific category.  
In regression, we use expected values instead of probabilities. But this is actually the same thing since both are sum divided by count. That's why it also works for regression.  
For details I'd also recommend looking at the original paper: https://dl.acm.org/citation.cfm?id=507538
