### ISSUE TITLE
LeaveOneOutEncoder(return_df=False) returns pd.DataFrame

### ISSUE THREAD

**Issue by Yura52** [scikit-learn-contrib/category_encoders#287]
```python
from category_encoders import LeaveOneOutEncoder
import numpy as np
import pandas as pd

X = np.random.randint(0, 3, (10, 2))
y = np.random.randn(10)
loo = LeaveOneOutEncoder(sigma=0.1, random_state=0, return_df=False)
assert isinstance(loo.fit_transform(X, y), pd.DataFrame)
```

```
python==3.8.5
category_encoders==2.2.2
pandas==1.2.0
numpy==1.19.4
```

**Comment by PaulWestenthanner** [comment]
The case you describe is sort of an edge case. Since you do not specify columns, all object type columns will be encoded which is none in your case. For the "nothing-to-encodet" case we actually just return the input and ignore the `return_df` parameter (however we first convert everything to pandas datatypes). The current behaviour does not make sense and should be changed to either return the input if there is nothing to encode or actually use the `return_df` parameter

**Comment by PaulWestenthanner** [comment]
Basically the same as discussed in #237
