### ISSUE TITLE
LeaveOneOutEncoder - Inconsistent behaviour and bug

### ISSUE THREAD

**Issue by nilslacroix** [scikit-learn-contrib/category_encoders#310]
## Expected Behavior
perform fit_transform(X, y=None)

## Actual Behavior
In comparison to OneHotEncoder or BinaryEncoder, LeaveOneOutEncoder produces the error:

fit_transform() missing argument: y

This is incosistent with the other encoders, which do not produce this error. The problem is the encoders
are part of a preprocessing pipeline which is applied not only to my estimators. For example:

I calculate gamma myself, which is only based on X. When I write pipe.fit(X) however, this is not possible anymore
with this encoder.

## Steps to Reproduce the Problem

  1. Put the encoder in a pipeline
  2. Call pipe.fit only on X
  3. Error

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by PaulWestenthanner** [comment]
Hi @nilslacroix 
This is actually the expected behaviour.  
Some encoders in the category encoders package also require target information like the LeaveOneOut encoder whereas others don't like OneHotEncoding. Obviously encoders that use the target for encoding will raise an error if called without a target.  
Unfortunately the link given in the documentation of LeaveOneOutEncoder, that point to how the algorithm works, is broken.
